image: openjdk:8-jdk-alpine
pipelines:
  default:
    - step:
        script:
          - docker login -u bereketdeb1 -p Holly6263@
          - docker build -t bereketdeb1/say-hello:latest .
          - docker push bereketdeb1/say-hello:latest
options:
  docker: true