image: maven:3.6.1
pipelines:
  default:
    - step:
        script:
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          - docker build -t bereketdeb1/say-hello:latest .
          - docker push bereketdeb1/say-hello:latest
options:
  docker: true